In [1]:
import pandas as pd
from pandas import Series, DataFrame
training_data = pd.read_csv('train.csv')

In [2]:
training_data

,TRANSFER,685452.64,C1704791286,0.0,0.0.1,C438188216,1.205051826E7,1.27359709E7,0
0,PAYMENT,6392.99,C290472726,0.00,0.00,M1724702465,0.00,0.00,0
1,CASH_IN,231808.89,C2132668204,3828.00,235636.89,C1150636366,932955.82,701146.94,0
2,CASH_IN,259576.11,C104203285,5867458.24,6127034.35,C1026383441,282591.51,23015.40,0
3,CASH_IN,97990.47,C1500302228,1199155.99,1297146.47,C1053392239,322949.21,224958.74,0
4,PAYMENT,17146.57,C158362520,79530.00,62383.43,M1559938202,0.00,0.00,0
5,CASH_IN,60447.57,C708610822,15386241.48,15446689.05,C1383112954,3952249.58,4109623.42,0
6,PAYMENT,8953.89,C130266936,0.00,0.00,M1459816802,0.00,0.00,0
7,PAYMENT,44106.18,C1547214391,2256.00,0.00,M70496520,0.00,0.00,0
8,CASH_OUT,222235.49,C2072161055,0.00,0.00,C2050019814,5151740.59,5213423.73,0
9,CASH_IN,277002.65,C380468559,15193.00,292195.65,C16003322,0.00,0.00,0
10,PAYMENT,7750.39,C672226199,273910.95,266160.56,M1529533115,0.00,0.00,0
11,TRANSFER,1551633.18,C617778349,0.00,0.00,C754887543,2844565.19,3445779.88,0
12,CASH_IN,293042.34,C1492019544,707782.76,1000825.10,C267906819,307745.79,14703.44,0
13,CASH_OUT,27182.52,C675416828,0.00,0.00,C2029518292,359525.05,386707.57,0
14,CASH_OUT,114647.25,C440708219,70538.00,0.00,C2017318515,99535.81,214183.06,0
15,PAYMENT,6744.74,C1310146849,0.00,0.00,M560730614,0.00,0.00,0
16,PAYMENT,3235.55,C446577374,328594.53,325358.99,M1841895762,0.00,0.00,0
17,PAYMENT,3507.36,C910479000,0.00,0.00,M1975891279,0.00,0.00,0
18,CASH_OUT,122108.63,C1509452962,0.00,0.00,C579882629,207434.04,329542.67,0
19,CASH_OUT,114656.77,C475195102,15249.00,0.00,C1151328915,530972.61,645629.38,0
20,CASH_OUT,527400.47,C472265625,149646.00,0.00,C326738344,0.00,527400.47,0
21,PAYMENT,6319.22,C266463384,0.00,0.00,M272879366,0.00,0.00,0
22,PAYMENT,7270.53,C50931206,0.00,0.00,M87757242,0.00,0.00,0
23,PAYMENT,853.72,C2054818010,35133.00,34279.28,M1301660824,0.00,0.00,0
24,TRANSFER,217306.60,C1148599951,30775.00,0.00,C2002453856,62685.81,279992.41,0
25,CASH_OUT,118913.12,C112944873,77194.00,0.00,C243773315,130136.01,249049.13,0
26,CASH_OUT,128332.95,C132211305,0.00,0.00,C680058794,11447431.73,11681596.89,0
27,PAYMENT,5605.65,C515988007,0.00,0.00,M253693623,0.00,0.00,0
28,PAYMENT,2761.63,C703430382,0.00,0.00,M1647558344,0.00,0.00,0
29,PAYMENT,24497.07,C1175927193,0.00,0.00,M1433748950,0.00,0.00,0
...,...,...,...,...,...,...,...,...,...
1999969,CASH_OUT,127811.43,C1158403801,3023.00,0.00,C1105241321,0.00,127811.43,0
1999970,PAYMENT,16427.68,C582303611,29463.00,13035.32,M638679758,0.00,0.00,0
1999971,PAYMENT,22815.10,C1167597913,49901.00,27085.90,M564094152,0.00,0.00,0
1999972,CASH_OUT,267429.70,C2082967631,0.00,0.00,C396769460,2284228.33,2551658.03,0
1999973,CASH_OUT,217190.03,C803169810,1967.00,0.00,C2104062472,0.00,217190.03,0
1999974,CASH_IN,4765.13,C1645185603,1270891.57,1275656.70,C447778686,23280.65,0.00,0
1999975,CASH_IN,301364.83,C1495761283,7464154.54,7765519.36,C489421462,1302620.48,1001255.65,0
1999976,TRANSFER,479988.84,C50266485,0.00,0.00,C627562887,1235953.72,1715942.56,0
1999977,CASH_OUT,128690.93,C607807993,6083.00,0.00,C1147138744,10931.00,31526.74,0
1999978,PAYMENT,2877.26,C372593175,192608.00,189730.74,M196272111,0.00,0.00,0
1999979,PAYMENT,13291.25,C1800350997,0.00,0.00,M531380974,0.00,0.00,0
1999980,PAYMENT,2463.34,C640210654,0.00,0.00,M900143224,0.00,0.00,0
1999981,PAYMENT,4748.98,C749583607,21190.00,16441.02,M1983289625,0.00,0.00,0
1999982,PAYMENT,3330.51,C1564984241,0.00,0.00,M2011923944,0.00,0.00,0
1999983,CASH_OUT,11629.52,C1885832327,25866.00,14236.48,C124855175,579859.29,591488.80,0
1999984,CASH_IN,436889.59,C1350395756,5074.00,441963.59,C391683289,5722838.84,5285949.25,0
1999985,CASH_OUT,128575.66,C204234900,0.00,0.00,C1623108387,163884.12,110350.25,0
1999986,TRANSFER,122839.53,C1943628293,0.00,0.00,C1251838000,9099034.33,9221873.86,0
1999987,CASH_OUT,150471.11,C2061931251,0.00,0.00,C400053994,372337.71,1099437.24,0
1999988,PAYMENT,2565.16,C1757247416,2073.00,0.00,M543130980,0.00,0.00,0
1999989,PAYMENT,17011.99,C1509134070,0.00,0.00,M400994893,0.00,0.00,0
1999990,PAYMENT,6206.44,C2104691147,11193.00,4986.56,M1601497364,0.00,0.00,0
1999991,CASH_OUT,215632.37,C664606567,21439.00,0.00,C1648187766,37717.93,253350.30,0
1999992,CASH_OUT,523209.62,C120238907,0.00,0.00,C1435796766,710020.29,1233229.91,0
1999993,CASH_OUT,276515.48,C1230425017,192442.00,0.00,C917091212,144315.33,0.00,0
1999994,PAYMENT,13602.09,C718417865,61529.90,47927.80,M65534265,0.00,0.00,0
1999995,CASH_OUT,99167.54,C1260376229,0.00,0.00,C1126244209,175078.00,274245.55,0
1999996,PAYMENT,17360.97,C656958804,0.00,0.00,M1098333863,0.00,0.00,0
1999997,CASH_IN,177611.83,C1947325401,623065.62,800677.45,C265359861,1880744.52,3025265.78,0
1999998,CASH_OUT,122339.39,C903761280,50873.00,0.00,C1726103926,428295.08,550634.47,0

In [3]:
'''adding header to dataframe'''
training_data.columns = ["type", "montant", "compteSource","sourceAvant", "sourceApres","compteDist","distAvant","distApres","isFraud"]

In [4]:
training_data

,type,montant,compteSource,sourceAvant,sourceApres,compteDist,distAvant,distApres,isFraud
0,PAYMENT,6392.99,C290472726,0.00,0.00,M1724702465,0.00,0.00,0
1,CASH_IN,231808.89,C2132668204,3828.00,235636.89,C1150636366,932955.82,701146.94,0
2,CASH_IN,259576.11,C104203285,5867458.24,6127034.35,C1026383441,282591.51,23015.40,0
3,CASH_IN,97990.47,C1500302228,1199155.99,1297146.47,C1053392239,322949.21,224958.74,0
4,PAYMENT,17146.57,C158362520,79530.00,62383.43,M1559938202,0.00,0.00,0
5,CASH_IN,60447.57,C708610822,15386241.48,15446689.05,C1383112954,3952249.58,4109623.42,0
6,PAYMENT,8953.89,C130266936,0.00,0.00,M1459816802,0.00,0.00,0
7,PAYMENT,44106.18,C1547214391,2256.00,0.00,M70496520,0.00,0.00,0
8,CASH_OUT,222235.49,C2072161055,0.00,0.00,C2050019814,5151740.59,5213423.73,0
9,CASH_IN,277002.65,C380468559,15193.00,292195.65,C16003322,0.00,0.00,0
10,PAYMENT,7750.39,C672226199,273910.95,266160.56,M1529533115,0.00,0.00,0
11,TRANSFER,1551633.18,C617778349,0.00,0.00,C754887543,2844565.19,3445779.88,0
12,CASH_IN,293042.34,C1492019544,707782.76,1000825.10,C267906819,307745.79,14703.44,0
13,CASH_OUT,27182.52,C675416828,0.00,0.00,C2029518292,359525.05,386707.57,0
14,CASH_OUT,114647.25,C440708219,70538.00,0.00,C2017318515,99535.81,214183.06,0
15,PAYMENT,6744.74,C1310146849,0.00,0.00,M560730614,0.00,0.00,0
16,PAYMENT,3235.55,C446577374,328594.53,325358.99,M1841895762,0.00,0.00,0
17,PAYMENT,3507.36,C910479000,0.00,0.00,M1975891279,0.00,0.00,0
18,CASH_OUT,122108.63,C1509452962,0.00,0.00,C579882629,207434.04,329542.67,0
19,CASH_OUT,114656.77,C475195102,15249.00,0.00,C1151328915,530972.61,645629.38,0
20,CASH_OUT,527400.47,C472265625,149646.00,0.00,C326738344,0.00,527400.47,0
21,PAYMENT,6319.22,C266463384,0.00,0.00,M272879366,0.00,0.00,0
22,PAYMENT,7270.53,C50931206,0.00,0.00,M87757242,0.00,0.00,0
23,PAYMENT,853.72,C2054818010,35133.00,34279.28,M1301660824,0.00,0.00,0
24,TRANSFER,217306.60,C1148599951,30775.00,0.00,C2002453856,62685.81,279992.41,0
25,CASH_OUT,118913.12,C112944873,77194.00,0.00,C243773315,130136.01,249049.13,0
26,CASH_OUT,128332.95,C132211305,0.00,0.00,C680058794,11447431.73,11681596.89,0
27,PAYMENT,5605.65,C515988007,0.00,0.00,M253693623,0.00,0.00,0
28,PAYMENT,2761.63,C703430382,0.00,0.00,M1647558344,0.00,0.00,0
29,PAYMENT,24497.07,C1175927193,0.00,0.00,M1433748950,0.00,0.00,0
...,...,...,...,...,...,...,...,...,...
1999969,CASH_OUT,127811.43,C1158403801,3023.00,0.00,C1105241321,0.00,127811.43,0
1999970,PAYMENT,16427.68,C582303611,29463.00,13035.32,M638679758,0.00,0.00,0
1999971,PAYMENT,22815.10,C1167597913,49901.00,27085.90,M564094152,0.00,0.00,0
1999972,CASH_OUT,267429.70,C2082967631,0.00,0.00,C396769460,2284228.33,2551658.03,0
1999973,CASH_OUT,217190.03,C803169810,1967.00,0.00,C2104062472,0.00,217190.03,0
1999974,CASH_IN,4765.13,C1645185603,1270891.57,1275656.70,C447778686,23280.65,0.00,0
1999975,CASH_IN,301364.83,C1495761283,7464154.54,7765519.36,C489421462,1302620.48,1001255.65,0
1999976,TRANSFER,479988.84,C50266485,0.00,0.00,C627562887,1235953.72,1715942.56,0
1999977,CASH_OUT,128690.93,C607807993,6083.00,0.00,C1147138744,10931.00,31526.74,0
1999978,PAYMENT,2877.26,C372593175,192608.00,189730.74,M196272111,0.00,0.00,0
1999979,PAYMENT,13291.25,C1800350997,0.00,0.00,M531380974,0.00,0.00,0
1999980,PAYMENT,2463.34,C640210654,0.00,0.00,M900143224,0.00,0.00,0
1999981,PAYMENT,4748.98,C749583607,21190.00,16441.02,M1983289625,0.00,0.00,0
1999982,PAYMENT,3330.51,C1564984241,0.00,0.00,M2011923944,0.00,0.00,0
1999983,CASH_OUT,11629.52,C1885832327,25866.00,14236.48,C124855175,579859.29,591488.80,0
1999984,CASH_IN,436889.59,C1350395756,5074.00,441963.59,C391683289,5722838.84,5285949.25,0
1999985,CASH_OUT,128575.66,C204234900,0.00,0.00,C1623108387,163884.12,110350.25,0
1999986,TRANSFER,122839.53,C1943628293,0.00,0.00,C1251838000,9099034.33,9221873.86,0
1999987,CASH_OUT,150471.11,C2061931251,0.00,0.00,C400053994,372337.71,1099437.24,0
1999988,PAYMENT,2565.16,C1757247416,2073.00,0.00,M543130980,0.00,0.00,0
1999989,PAYMENT,17011.99,C1509134070,0.00,0.00,M400994893,0.00,0.00,0
1999990,PAYMENT,6206.44,C2104691147,11193.00,4986.56,M1601497364,0.00,0.00,0
1999991,CASH_OUT,215632.37,C664606567,21439.00,0.00,C1648187766,37717.93,253350.30,0
1999992,CASH_OUT,523209.62,C120238907,0.00,0.00,C1435796766,710020.29,1233229.91,0
1999993,CASH_OUT,276515.48,C1230425017,192442.00,0.00,C917091212,144315.33,0.00,0
1999994,PAYMENT,13602.09,C718417865,61529.90,47927.80,M65534265,0.00,0.00,0
1999995,CASH_OUT,99167.54,C1260376229,0.00,0.00,C1126244209,175078.00,274245.55,0
1999996,PAYMENT,17360.97,C656958804,0.00,0.00,M1098333863,0.00,0.00,0
1999997,CASH_IN,177611.83,C1947325401,623065.62,800677.45,C265359861,1880744.52,3025265.78,0
1999998,CASH_OUT,122339.39,C903761280,50873.00,0.00,C1726103926,428295.08,550634.47,0

In [5]:
'''test if there is any null values'''
training_data.isnull().values.any()

False

In [6]:
'''Get the  type of transactions that are fraud'''
list(training_data.loc[training_data.isFraud == 1].type.drop_duplicates().values)

['TRANSFER', 'CASH_OUT']

In [7]:
'''At first we were going to train our model only with the fraud data,but we realized that this was not correct'''
trainingFraudTransfer = training_data.loc[(training_data.type == 'TRANSFER')]
trainingFraudCashout = training_data.loc[(training_data.type == 'CASH_OUT')]
trainingResult = pd.concat([trainingFraudTransfer,trainingFraudCashout]);
trainingResult

,type,montant,compteSource,sourceAvant,sourceApres,compteDist,distAvant,distApres,isFraud
11,TRANSFER,1551633.18,C617778349,0.00,0.00,C754887543,2844565.19,3445779.88,0
24,TRANSFER,217306.60,C1148599951,30775.00,0.00,C2002453856,62685.81,279992.41,0
49,TRANSFER,367990.70,C1907514349,106753.00,0.00,C1750636426,308442.23,676432.94,0
50,TRANSFER,356885.97,C993653142,253.00,0.00,C307415869,0.00,356885.97,0
51,TRANSFER,146931.21,C2089509066,0.00,0.00,C424898921,4769237.72,4916168.93,0
53,TRANSFER,419014.75,C1717325245,0.00,0.00,C769591652,8010598.57,8799718.90,0
56,TRANSFER,162916.45,C180516057,162.00,0.00,C443298466,771392.66,934309.11,0
66,TRANSFER,539330.48,C998488963,415534.53,0.00,C239855125,1251853.38,1791183.86,0
72,TRANSFER,2696247.25,C1059872581,0.00,0.00,C679235222,7060675.50,9558268.86,0
73,TRANSFER,455263.57,C892324975,263016.11,0.00,C260071235,3109526.91,3564790.48,0
82,TRANSFER,797182.12,C1705072324,0.00,0.00,C1944110965,6231764.79,7028946.90,0
85,TRANSFER,911963.03,C2136821202,0.00,0.00,C496375403,2636177.90,3548140.94,0
87,TRANSFER,1247360.79,C954825910,0.00,0.00,C795982694,4392681.73,5640042.53,0
94,TRANSFER,207602.20,C589990275,50218.00,0.00,C607702142,2988563.53,3196165.73,0
97,TRANSFER,15015.46,C1540641660,105821.00,90805.54,C1647831058,0.00,15015.46,0
111,TRANSFER,210413.69,C1932426248,25199.55,0.00,C1854453853,1609798.80,1820212.50,0
134,TRANSFER,56943.87,C1637750516,0.00,0.00,C2012125907,679670.49,736614.36,0
147,TRANSFER,196037.42,C890338036,0.00,0.00,C1523625503,3038582.32,3187517.58,0
193,TRANSFER,521868.90,C1756702638,1217276.25,695407.36,C263035923,49507.00,571375.90,0
200,TRANSFER,649553.01,C878823830,0.00,0.00,C515578013,782418.87,1431971.87,0
206,TRANSFER,80158.09,C702546108,1523.00,0.00,C1554835700,0.00,80158.09,0
221,TRANSFER,166449.62,C2034552365,364865.31,198415.69,C64174944,295657.52,462107.14,0
224,TRANSFER,486016.49,C580318793,0.00,0.00,C66941603,918851.39,1404867.88,0
250,TRANSFER,178520.00,C1001672646,0.00,0.00,C1891932276,1317318.04,1495838.04,0
257,TRANSFER,450073.94,C1936591219,106976.00,0.00,C2066777507,3277.29,208425.97,0
258,TRANSFER,1010999.50,C188682331,1003608.62,0.00,C606815938,6175206.74,7312045.07,0
263,TRANSFER,497523.77,C1399648347,0.00,0.00,C1548704437,2094751.78,2592275.55,0
269,TRANSFER,766597.06,C522427663,39153.00,0.00,C2107746501,1262857.83,2029454.89,0
270,TRANSFER,390549.00,C1455615529,0.00,0.00,C2067847926,2351815.10,2675354.81,0
283,TRANSFER,1208273.40,C277342097,159630.00,0.00,C435365761,2209088.41,3417361.81,0
...,...,...,...,...,...,...,...,...,...
1999914,CASH_OUT,213269.41,C611716373,11300.00,0.00,C1297426398,0.00,213269.41,0
1999915,CASH_OUT,102210.77,C748248174,0.00,0.00,C988625655,172884.62,236933.32,0
1999919,CASH_OUT,339599.79,C1998087058,57002.00,0.00,C542135723,0.00,631301.82,0
1999927,CASH_OUT,211397.00,C956274809,49777.00,0.00,C275714876,5681402.92,5892799.92,0
1999929,CASH_OUT,53934.98,C1520378452,29732.00,0.00,C1379319395,3916663.60,3828964.22,0
1999932,CASH_OUT,248491.49,C1087788640,4217.00,0.00,C222551706,2421756.01,2670247.50,0
1999939,CASH_OUT,382041.82,C358701292,158.00,0.00,C1719097828,115878.03,497919.85,0
1999944,CASH_OUT,130845.59,C214225847,0.00,0.00,C695574584,813191.82,944037.41,0
1999946,CASH_OUT,312463.86,C433781659,0.00,0.00,C1286237039,721595.73,1034059.59,0
1999950,CASH_OUT,7773.99,C1325095780,832693.18,824919.19,C546495530,97759.79,105533.78,0
1999954,CASH_OUT,20094.55,C353413777,0.00,0.00,C628088618,107799.00,43037.89,0
1999956,CASH_OUT,194368.25,C180802489,49853.00,0.00,C706259197,298704.93,665565.67,0
1999959,CASH_OUT,138690.83,C1586514842,0.00,0.00,C1375815098,10543450.36,11301516.01,0
1999960,CASH_OUT,39419.44,C4730090,0.00,0.00,C71242230,3439992.49,3479411.93,0
1999963,CASH_OUT,204707.70,C1415115850,0.00,0.00,C1007483565,1130567.45,1335275.15,0
1999964,CASH_OUT,276848.53,C344180198,14141.28,0.00,C1942085631,4859624.40,5136472.93,0
1999966,CASH_OUT,259336.99,C991274221,0.00,0.00,C872485269,3288933.64,3548270.63,0
1999967,CASH_OUT,79968.69,C1046007357,160226.00,80257.31,C1225390660,11025190.24,11105158.93,0
1999969,CASH_OUT,127811.43,C1158403801,3023.00,0.00,C1105241321,0.00,127811.43,0
1999972,CASH_OUT,267429.70,C2082967631,0.00,0.00,C396769460,2284228.33,2551658.03,0
1999973,CASH_OUT,217190.03,C803169810,1967.00,0.00,C2104062472,0.00,217190.03,0
1999977,CASH_OUT,128690.93,C607807993,6083.00,0.00,C1147138744,10931.00,31526.74,0
1999983,CASH_OUT,11629.52,C1885832327,25866.00,14236.48,C124855175,579859.29,591488.80,0
1999985,CASH_OUT,128575.66,C204234900,0.00,0.00,C1623108387,163884.12,110350.25,0
1999987,CASH_OUT,150471.11,C2061931251,0.00,0.00,C400053994,372337.71,1099437.24,0
1999991,CASH_OUT,215632.37,C664606567,21439.00,0.00,C1648187766,37717.93,253350.30,0
1999992,CASH_OUT,523209.62,C120238907,0.00,0.00,C1435796766,710020.29,1233229.91,0
1999993,CASH_OUT,276515.48,C1230425017,192442.00,0.00,C917091212,144315.33,0.00,0
1999995,CASH_OUT,99167.54,C1260376229,0.00,0.00,C1126244209,175078.00,274245.55,0
1999998,CASH_OUT,122339.39,C903761280,50873.00,0.00,C1726103926,428295.08,550634.47,0

In [8]:
'''Transforming the account numbers to strings'''
training_data['OrigC']=training_data['compteSource'].apply(lambda x: 1 if str(x).find('C')==0 else 0)
training_data['DestC']=training_data['compteDist'].apply(lambda x: 1 if str(x).find('C')==0 else 0)
#if it's not a transfer it's a cash out

In [9]:
'''Function to convert the type'''
def make_labels(row):
    if row == 'TRANSFER':
        return 1
    elif row == 'CASH_IN':
        return 2
    elif row == 'DEBIT':
        return 3
    elif row == 'PAYMENT':
        return 4
    else:
        return 0

In [10]:
training_data['type_id']=training_data['type'].apply(make_labels)
'''Spilitting the data to X and Y'''
train_data_X = training_data[['type_id', 'montant', 'OrigC', 'sourceAvant', 'sourceApres', 'DestC', 'distApres']].copy()
train_data_y = training_data[['isFraud']].copy()
training_data

,type,montant,compteSource,sourceAvant,sourceApres,compteDist,distAvant,distApres,isFraud,OrigC,DestC,type_id
0,PAYMENT,6392.99,C290472726,0.00,0.00,M1724702465,0.00,0.00,0,1,0,4
1,CASH_IN,231808.89,C2132668204,3828.00,235636.89,C1150636366,932955.82,701146.94,0,1,1,2
2,CASH_IN,259576.11,C104203285,5867458.24,6127034.35,C1026383441,282591.51,23015.40,0,1,1,2
3,CASH_IN,97990.47,C1500302228,1199155.99,1297146.47,C1053392239,322949.21,224958.74,0,1,1,2
4,PAYMENT,17146.57,C158362520,79530.00,62383.43,M1559938202,0.00,0.00,0,1,0,4
5,CASH_IN,60447.57,C708610822,15386241.48,15446689.05,C1383112954,3952249.58,4109623.42,0,1,1,2
6,PAYMENT,8953.89,C130266936,0.00,0.00,M1459816802,0.00,0.00,0,1,0,4
7,PAYMENT,44106.18,C1547214391,2256.00,0.00,M70496520,0.00,0.00,0,1,0,4
8,CASH_OUT,222235.49,C2072161055,0.00,0.00,C2050019814,5151740.59,5213423.73,0,1,1,0
9,CASH_IN,277002.65,C380468559,15193.00,292195.65,C16003322,0.00,0.00,0,1,1,2
10,PAYMENT,7750.39,C672226199,273910.95,266160.56,M1529533115,0.00,0.00,0,1,0,4
11,TRANSFER,1551633.18,C617778349,0.00,0.00,C754887543,2844565.19,3445779.88,0,1,1,1
12,CASH_IN,293042.34,C1492019544,707782.76,1000825.10,C267906819,307745.79,14703.44,0,1,1,2
13,CASH_OUT,27182.52,C675416828,0.00,0.00,C2029518292,359525.05,386707.57,0,1,1,0
14,CASH_OUT,114647.25,C440708219,70538.00,0.00,C2017318515,99535.81,214183.06,0,1,1,0
15,PAYMENT,6744.74,C1310146849,0.00,0.00,M560730614,0.00,0.00,0,1,0,4
16,PAYMENT,3235.55,C446577374,328594.53,325358.99,M1841895762,0.00,0.00,0,1,0,4
17,PAYMENT,3507.36,C910479000,0.00,0.00,M1975891279,0.00,0.00,0,1,0,4
18,CASH_OUT,122108.63,C1509452962,0.00,0.00,C579882629,207434.04,329542.67,0,1,1,0
19,CASH_OUT,114656.77,C475195102,15249.00,0.00,C1151328915,530972.61,645629.38,0,1,1,0
20,CASH_OUT,527400.47,C472265625,149646.00,0.00,C326738344,0.00,527400.47,0,1,1,0
21,PAYMENT,6319.22,C266463384,0.00,0.00,M272879366,0.00,0.00,0,1,0,4
22,PAYMENT,7270.53,C50931206,0.00,0.00,M87757242,0.00,0.00,0,1,0,4
23,PAYMENT,853.72,C2054818010,35133.00,34279.28,M1301660824,0.00,0.00,0,1,0,4
24,TRANSFER,217306.60,C1148599951,30775.00,0.00,C2002453856,62685.81,279992.41,0,1,1,1
25,CASH_OUT,118913.12,C112944873,77194.00,0.00,C243773315,130136.01,249049.13,0,1,1,0
26,CASH_OUT,128332.95,C132211305,0.00,0.00,C680058794,11447431.73,11681596.89,0,1,1,0
27,PAYMENT,5605.65,C515988007,0.00,0.00,M253693623,0.00,0.00,0,1,0,4
28,PAYMENT,2761.63,C703430382,0.00,0.00,M1647558344,0.00,0.00,0,1,0,4
29,PAYMENT,24497.07,C1175927193,0.00,0.00,M1433748950,0.00,0.00,0,1,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...
1999969,CASH_OUT,127811.43,C1158403801,3023.00,0.00,C1105241321,0.00,127811.43,0,1,1,0
1999970,PAYMENT,16427.68,C582303611,29463.00,13035.32,M638679758,0.00,0.00,0,1,0,4
1999971,PAYMENT,22815.10,C1167597913,49901.00,27085.90,M564094152,0.00,0.00,0,1,0,4
1999972,CASH_OUT,267429.70,C2082967631,0.00,0.00,C396769460,2284228.33,2551658.03,0,1,1,0
1999973,CASH_OUT,217190.03,C803169810,1967.00,0.00,C2104062472,0.00,217190.03,0,1,1,0
1999974,CASH_IN,4765.13,C1645185603,1270891.57,1275656.70,C447778686,23280.65,0.00,0,1,1,2
1999975,CASH_IN,301364.83,C1495761283,7464154.54,7765519.36,C489421462,1302620.48,1001255.65,0,1,1,2
1999976,TRANSFER,479988.84,C50266485,0.00,0.00,C627562887,1235953.72,1715942.56,0,1,1,1
1999977,CASH_OUT,128690.93,C607807993,6083.00,0.00,C1147138744,10931.00,31526.74,0,1,1,0
1999978,PAYMENT,2877.26,C372593175,192608.00,189730.74,M196272111,0.00,0.00,0,1,0,4
1999979,PAYMENT,13291.25,C1800350997,0.00,0.00,M531380974,0.00,0.00,0,1,0,4
1999980,PAYMENT,2463.34,C640210654,0.00,0.00,M900143224,0.00,0.00,0,1,0,4
1999981,PAYMENT,4748.98,C749583607,21190.00,16441.02,M1983289625,0.00,0.00,0,1,0,4
1999982,PAYMENT,3330.51,C1564984241,0.00,0.00,M2011923944,0.00,0.00,0,1,0,4
1999983,CASH_OUT,11629.52,C1885832327,25866.00,14236.48,C124855175,579859.29,591488.80,0,1,1,0
1999984,CASH_IN,436889.59,C1350395756,5074.00,441963.59,C391683289,5722838.84,5285949.25,0,1,1,2
1999985,CASH_OUT,128575.66,C204234900,0.00,0.00,C1623108387,163884.12,110350.25,0,1,1,0
1999986,TRANSFER,122839.53,C1943628293,0.00,0.00,C1251838000,9099034.33,9221873.86,0,1,1,1
1999987,CASH_OUT,150471.11,C2061931251,0.00,0.00,C400053994,372337.71,1099437.24,0,1,1,0
1999988,PAYMENT,2565.16,C1757247416,2073.00,0.00,M543130980,0.00,0.00,0,1,0,4
1999989,PAYMENT,17011.99,C1509134070,0.00,0.00,M400994893,0.00,0.00,0,1,0,4
1999990,PAYMENT,6206.44,C2104691147,11193.00,4986.56,M1601497364,0.00,0.00,0,1,0,4
1999991,CASH_OUT,215632.37,C664606567,21439.00,0.00,C1648187766,37717.93,253350.30,0,1,1,0
1999992,CASH_OUT,523209.62,C120238907,0.00,0.00,C1435796766,710020.29,1233229.91,0,1,1,0
1999993,CASH_OUT,276515.48,C1230425017,192442.00,0.00,C917091212,144315.33,0.00,0,1,1,0
1999994,PAYMENT,13602.09,C718417865,61529.90,47927.80,M65534265,0.00,0.00,0,1,0,4
1999995,CASH_OUT,99167.54,C1260376229,0.00,0.00,C1126244209,175078.00,274245.55,0,1,1,0
1999996,PAYMENT,17360.97,C656958804,0.00,0.00,M1098333863,0.00,0.00,0,1,0,4
1999997,CASH_IN,177611.83,C1947325401,623065.62,800677.45,C265359861,1880744.52,3025265.78,0,1,1,2
1999998,CASH_OUT,122339.39,C903761280,50873.00,0.00,C1726103926,428295.08,550634.47,0,1,1,0

In [11]:
'''importing our test data and processing it as the train data'''
test_data = pd.read_csv('test.csv')
test_data.columns = ["type", "montant", "compteSource","sourceAvant", "sourceApres","compteDist","distAvant","distApres","isFraud"]
list(test_data.loc[test_data.isFraud == 1].type.drop_duplicates().values)

['TRANSFER', 'CASH_OUT']

In [12]:
'''dataset only with the fraud test data'''
testFraudTransfer = test_data.loc[(test_data.type == 'TRANSFER')]
testFraudCashout = test_data.loc[(test_data.type == 'CASH_OUT')]
testResult = pd.concat([testFraudTransfer,testFraudCashout]);

In [13]:
'''Transform of the train data set'''
test_data['OrigC']=test_data['compteSource'].apply(lambda x: 1 if str(x).find('C')==0 else 0)
test_data['DestC']=test_data['compteDist'].apply(lambda x: 1 if str(x).find('C')==0 else 0)
#if it's not a transfer it's a cash out
test_data['type_id']=test_data['type'].apply(make_labels)
test_data_X = test_data[['type_id', 'montant', 'OrigC', 'sourceAvant', 'sourceApres', 'DestC', 'distApres']].copy()
test_data_y = test_data[['isFraud']].copy()
test_data

,type,montant,compteSource,sourceAvant,sourceApres,compteDist,distAvant,distApres,isFraud,OrigC,DestC,type_id
0,TRANSFER,1158070.88,C278936084,1158070.88,0.00,C1115591594,0.00,0.00,1,1,1,1
1,CASH_OUT,67128.33,C489879149,67128.33,0.00,C813701633,623880.13,691008.45,1,1,1,0
2,CASH_OUT,495002.26,C1881438255,25008.00,0.00,C1258128467,0.00,495002.26,0,1,1,0
3,TRANSFER,615954.92,C114731289,615954.92,0.00,C236726278,0.00,0.00,1,1,1,1
4,CASH_OUT,8994286.69,C180006321,8994286.69,0.00,C1877082345,0.00,8994286.69,1,1,1,0
5,CASH_OUT,623152.72,C2031063966,623152.72,0.00,C1705815867,847223.26,1470375.97,1,1,1,0
6,PAYMENT,17206.91,C507644739,90836.00,73629.09,M893664024,0.00,0.00,0,1,0,4
7,PAYMENT,20099.71,C1048703966,77758.49,57658.77,M45490020,0.00,0.00,0,1,0,4
8,CASH_OUT,220799.50,C1652855106,0.00,0.00,C1612990285,394666.15,615465.65,0,1,1,0
9,CASH_OUT,146729.67,C661431090,146729.67,0.00,C249687884,0.00,146729.67,1,1,1,0
10,CASH_OUT,277995.36,C994995979,0.00,0.00,C1128494851,3404746.04,3682741.40,0,1,1,0
11,PAYMENT,37027.60,C480325182,41895.00,4867.40,M1030268147,0.00,0.00,0,1,0,4
12,CASH_OUT,183363.36,C1749173056,36.00,0.00,C1534089715,189948.53,373311.89,0,1,1,0
13,CASH_OUT,80011.41,C1974186724,0.00,0.00,C220480254,3787625.78,3867637.20,0,1,1,0
14,CASH_OUT,54235.70,C898552679,54235.70,0.00,C1969225780,0.00,54235.70,1,1,1,0
15,TRANSFER,10000000.00,C1559534298,24339822.23,14339822.23,C1910926478,0.00,0.00,1,1,1,1
16,TRANSFER,2341474.44,C532100013,2341474.44,0.00,C586068817,0.00,0.00,1,1,1,1
17,CASH_OUT,10000000.00,C51318897,10000000.00,0.00,C259016801,0.00,10000000.00,1,1,1,0
18,CASH_OUT,34146.81,C1010935098,30386.73,0.00,C1020697488,14316427.10,14350573.91,0,1,1,0
19,CASH_OUT,1070857.97,C1513064965,1070857.97,0.00,C1686203571,0.00,1070857.97,1,1,1,0
20,CASH_OUT,186723.12,C548707582,880093.07,693369.94,C280358299,241366.76,428089.88,0,1,1,0
21,CASH_OUT,1396824.94,C1626069370,1396824.94,0.00,C724673427,25923.43,1422748.37,1,1,1,0
22,TRANSFER,429863.45,C1474347273,0.00,0.00,C91546760,5014430.58,5444294.03,0,1,1,1
23,PAYMENT,9846.21,C278863432,3106.00,0.00,M322415754,0.00,0.00,0,1,0,4
24,CASH_OUT,224248.42,C470538803,0.00,0.00,C1271828486,4130929.45,4355177.87,0,1,1,0
25,PAYMENT,14911.82,C644368790,36232.00,21320.18,M391141946,0.00,0.00,0,1,0,4
26,PAYMENT,19170.03,C686183013,0.00,0.00,M1834747759,0.00,0.00,0,1,0,4
27,TRANSFER,172344.30,C547948167,172344.30,0.00,C765807005,0.00,0.00,1,1,1,1
28,CASH_OUT,69559.23,C1316561777,0.00,0.00,C373787058,1119742.79,1189302.01,0,1,1,0
29,CASH_OUT,182082.51,C663145143,234.00,0.00,C1579669155,0.00,182082.51,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
7969,CASH_OUT,221077.97,C1895360219,221077.97,0.00,C1325018812,0.00,221077.97,1,1,1,0
7970,CASH_OUT,100110.51,C185595015,0.00,0.00,C1218590381,181665.76,281776.27,0,1,1,0
7971,CASH_OUT,29611.08,C779716783,29611.08,0.00,C1919160151,723084.29,752695.37,1,1,1,0
7972,CASH_IN,258116.12,C1545954726,10897.00,269013.12,C575597999,371959.27,113843.15,0,1,1,2
7973,CASH_OUT,76786.78,C866399775,10586.00,0.00,C448717385,0.00,76786.78,0,1,1,0
7974,CASH_OUT,437180.80,C1368642383,0.00,0.00,C1621981895,1311062.74,1748243.54,0,1,1,0
7975,CASH_OUT,65839.32,C78949380,0.00,0.00,C1326092597,1496067.99,1561907.31,0,1,1,0
7976,CASH_OUT,10000000.00,C97242201,10000000.00,0.00,C786701128,8496.86,10008496.86,1,1,1,0
7977,TRANSFER,973805.75,C10712954,973805.75,0.00,C354003512,0.00,0.00,1,1,1,1
7978,CASH_OUT,132840.51,C1342291189,0.00,0.00,C958275791,536461.14,669301.64,0,1,1,0
7979,CASH_OUT,1307156.17,C1140455895,1307156.17,0.00,C1640699182,273026.12,1580182.28,1,1,1,0
7980,CASH_OUT,4737833.35,C450630495,4737833.35,0.00,C1565281210,11580904.90,16318738.25,1,1,1,0
7981,CASH_IN,58888.73,C1936736276,3596037.84,3654926.58,C1397560676,664005.85,605117.11,0,1,1,2
7982,TRANSFER,80397.86,C1839358501,80397.86,0.00,C1153377397,0.00,0.00,1,1,1,1
7983,CASH_OUT,51416.07,C1252081364,51416.07,0.00,C327344476,62726.44,114142.52,1,1,1,0
7984,CASH_OUT,111289.98,C513096696,0.00,0.00,C693578659,1935545.57,2046835.55,0,1,1,0
7985,CASH_OUT,259985.22,C847117504,0.00,0.00,C934972212,270674.05,530659.28,0,1,1,0
7986,TRANSFER,1423627.83,C552198318,1423627.83,0.00,C341414106,0.00,0.00,1,1,1,1
7987,CASH_IN,303080.69,C1425839995,2394118.93,2697199.62,C691305199,500130.58,197049.89,0,1,1,2
7988,CASH_OUT,80437.21,C1386427648,33706.00,0.00,C1842524692,1208515.69,1288952.89,0,1,1,0
7989,PAYMENT,8037.50,C1679785401,410592.10,402554.60,M1861734006,0.00,0.00,0,1,0,4
7990,PAYMENT,834.10,C1370512408,33608.00,32773.90,M613693629,0.00,0.00,0,1,0,4
7991,CASH_OUT,186734.49,C2015710052,9337.00,0.00,C1448542929,2424870.48,2611604.96,0,1,1,0
7992,TRANSFER,10000000.00,C1198427314,10353874.22,353874.22,C532935388,0.00,0.00,1,1,1,1
7993,CASH_OUT,716273.17,C1917556280,716273.17,0.00,C1744308202,0.00,716273.17,1,1,1,0
7994,TRANSFER,625395.06,C1965889079,304.00,0.00,C1277946259,833998.98,1459394.04,0,1,1,1
7995,TRANSFER,807466.16,C1365547819,807466.16,0.00,C1383531200,0.00,0.00,1,1,1,1
7996,TRANSFER,130777.09,C527353912,130777.09,0.00,C99611102,0.00,0.00,1,1,1,1
7997,PAYMENT,217.33,C553925053,0.00,0.00,M1050343598,0.00,0.00,0,1,0,4
7998,CASH_OUT,57758.92,C419169063,0.00,0.00,C704679150,102784.98,160543.91,0,1,1,0

In [14]:
'''Transforming predict dataset'''
predict_data = pd.read_csv('predict.csv')
predict_data.columns = ["type", "montant", "compteSource","sourceAvant", "sourceApres","compteDist","distAvant","distApres"]
predict_data['OrigC']=predict_data['compteSource'].apply(lambda x: 1 if str(x).find('C')==0 else 0)
predict_data['DestC']=predict_data['compteDist'].apply(lambda x: 1 if str(x).find('C')==0 else 0)
#if it's not a transfer it's a cash out
predict_data['type_id']=predict_data['type'].apply(make_labels)
predict_data_X = predict_data[['type_id', 'montant', 'OrigC', 'sourceAvant', 'sourceApres', 'DestC', 'distApres']].copy()

In [15]:
##oversampling and undersampling
train_data_y.apply(pd.value_counts)

   isFraud
0  1997418
1     2581

In [16]:
train_data_X['type_id'].value_counts()

0    712076
4    668732
2    440136
1    165802
3     13253
Name: type_id, dtype: int64

In [17]:
print(train_data_X.loc[train_data_X['type_id']==1][0:10])

    type_id     montant  OrigC  sourceAvant  sourceApres  DestC   distApres
11        1  1551633.18      1         0.00          0.0      1  3445779.88
24        1   217306.60      1     30775.00          0.0      1   279992.41
49        1   367990.70      1    106753.00          0.0      1   676432.94
50        1   356885.97      1       253.00          0.0      1   356885.97
51        1   146931.21      1         0.00          0.0      1  4916168.93
53        1   419014.75      1         0.00          0.0      1  8799718.90
56        1   162916.45      1       162.00          0.0      1   934309.11
66        1   539330.48      1    415534.53          0.0      1  1791183.86
72        1  2696247.25      1         0.00          0.0      1  9558268.86
73        1   455263.57      1    263016.11          0.0      1  3564790.48

In [18]:
'''Function to undersample the data'''
def underSampling(df):
   return  pd.concat([
       df.loc[df['type_id']==0][0:600]
        ,df.loc[df['type_id']==1][0:600],
       df.loc[df['type_id']==2][0:460],
       df.loc[df['type_id']==3][0:460],
        df.loc[df['type_id']==4][0:460]

   ])

In [19]:
'''Creating the undersampled dataset'''
train_sampled = underSampling(training_data)

In [20]:
'''adding header to sampled data'''
train_sampled_X = training_data[['type_id', 'montant', 'OrigC', 'sourceAvant', 'sourceApres', 'DestC', 'distApres']].copy()
train_sampled_y = training_data[['isFraud']].copy()

In [ ]:
'''Decision tree algorithm on sampled dataset'''
import time
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(random_state=0)
t = time.process_time()
tree.fit(train_sampled_X, train_sampled_y)
elapsed_time = time.process_time() - t
training_accuracy = tree.score(train_sampled_X, train_sampled_y)
test_accuracy = tree.score(test_data_X, test_data_y)
print("Training accuracy:", training_accuracy)
print("Test accuracy:", test_accuracy)
print(elapsed_time)

In [ ]:
'''Decision tree algorithm on full dataset'''
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(random_state=0)
t = time.process_time()
tree.fit(train_data_X, train_data_y)
elapsed_time = time.process_time() - t
training_accuracy = tree.score(train_data_X, train_data_y)
test_accuracy = tree.score(test_data_X, test_data_y)
print("Training accuracy:", training_accuracy)
print("Test accuracy:", test_accuracy)
print(elapsed_time)

In [ ]:
'''The result of the predection'''
tree_results = tree.predict(predict_data_X)

In [23]:
import time

In [ ]:
'''Saving the data into a csv file'''
final_predict_data = pd.read_csv('predict.csv')
final_predict_data.columns = ["type", "montant", "compteSource","sourceAvant", "sourceApres","compteDist","distAvant","distApres"]
final_predict_data['isFraud']=tree_results
final_predict_data.to_csv("out.csv",header=False,index=False)

In [ ]:
'''K neighbors algorithm'''
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3)
t = time.process_time()
model.fit(train_sampled_X, train_sampled_y)
elapsed_time = time.process_time() - t
print(elapsed_time)

In [ ]:
'''Calculating the accuracy'''
print("Accuracy =", accuracy)
print("# Misclassified points =", (1 - accuracy) * len(test_data_X))

In [24]:
'''Linear Regression'''
from sklearn.linear_model import LinearRegression
# create model and train it
model = LinearRegression()
t = time.process_time()
model.fit(train_sampled_X, train_sampled_y)
elapsed_time = time.process_time() - t
print(elapsed_time)

3.8079927829999995

In [28]:
'''Logistic Regression'''
from sklearn.linear_model import LogisticRegression
c = 0.001
model = LogisticRegression(C=c)
t = time.process_time()
model.fit(train_sampled_X, train_sampled_y)
elapsed_time = time.process_time() - t
print(elapsed_time)
accuracy  = model.score(test_data_X, test_data_y)
print("Accuracy =", accuracy)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

27.44545940800026
Accuracy = 0.907363420428

In [26]:
'''Neural networks'''
from sklearn.neural_network import MLPClassifier

network = MLPClassifier()
t = time.process_time()
network.fit(train_sampled_X, train_sampled_y)
elapsed_time = time.process_time() - t
print(elapsed_time)

/usr/local/lib/python3.5/dist-packages/sklearn/neural_network/multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

3358.8351453319997

/usr/local/lib/python3.5/dist-packages/sklearn/neural_network/multilayer_perceptron.py:566: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")